[[news]]
date = "2026-08"
content = "I joined the Artificial Intelligence in Medicine (AIM) Group at CUHK. 🎉"

[[news]]
date = "2026-07"
content = "Our work has been accepted by Cell Reports Medicine. This is our first CNS sub-journal! 🎉"

[[news]]
date = "2026-04"
content = "I was named an Outstanding Graduate of Beijing and an Excellent Graduate of Peking University. 🎉"

[[news]]
date = "2025-11"
content = "Our papers have been accepted by JMIR Medical Informatics and IEEE JBHI. 🎉"

[[news]]
date = "2025-11"
content = "I am incredibly honored to be named a Student Paper Competition Finalist at the AMIA 2025 Annual Symposium in Atlanta, GA, USA. 🏆 Out of only 7 finalists selected worldwide, I was the only finalist from outside the United States. 🎉"

[[news]]
date = "2025-09"
content = "I received the PKU May 4th Scholarship and some honors from Peking University. 🎉"

[[news]]
date = "2025-07"
content = "I became deputy editor-in-chief of the official WeChat account of Peking University. ✨"

[[news]]
date = "2025-06"
content = "Our work has been accepted by JAMIA Open. 🎉"

[[news]]
date = "2024-12"
content = "Our work has been accepted by Kidney Medicine. 🎉"

[[news]]
date = "2024-09"
content = "I received the National Scholarship and some honors from Peking University. 🐮"

[[news]]
date = "2024-07"
content = "I became editor-in-chief of the Backend Team for the official WeChat account of Peking University. ✨"

[[news]]
date = "2024-05"
content = "Our work has been accepted by the Science Partner Journal Health Data Science. 🎉"

[[news]]
date = "2023-09"
content = "I was fortunate to join Prof. Kong's lab at Peking University. 🎉"
