[[news]]
date = "2026-05"
content = "I was very lucky to pass my master's thesis defense. 🎉"

[[news]]
date = "2026-04"
content = "I am fortunate to be named the Outstanding Graduate of Beijing and the Outstanding Graduate of Peking University. 🎉"

[[news]]
date = "2025-11"
content = "Our works have been accepted by JMIR Medical Informatics and IEEE JBHI. 🎉"

[[news]]
date = "2025-11"
content = "I am incredibly honored to be named a Student Paper Competition Finalist at the AMIA 2025 Annual Symposium in Atlanta, GA, USA. 🏆 Out of only 7 finalists selected worldwide, I was the only finalist from outside the United States. 🎉"

[[news]]
date = "2025-09"
content = "I received the PKU May 4th Scholarship and some honors from Peking University. 🎉"

[[news]]
date = "2025-07"
content = "I have assumed the position of Deputy Chief Editor of the Official WeChat Account of Peking University. 🎉"

[[news]]
date = "2025-06"
content = "Our work has been accepted by JAMIA Open. 🎉"

[[news]]
date = "2024-12"
content = "Our work has been accepted by Kidney Medicine. 🎉"

[[news]]
date = "2024-09"
content = "I received the National Scholarship and some honors from Peking University. 🎉"

[[news]]
date = "2024-07"
content = "I have assumed the position of Chief Editor of the Backend Team for the Official WeChat Account of Peking University. 🎉"

[[news]]
date = "2024-05"
content = "Our work has been accepted by the Science Partner Journal Health Data Science. 🎉"